homeassistant: 
  #  Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 32.0912
  longitude: 34.7776921
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 8
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jerusalem

  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

mqtt:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

logger:
  default: warning
  logs:
    homeassistant.components.device_tracker.mqtt: debug  
    #homeassistant.components.camera: fatal
    requests.packages.urllib3: critical
    #homeassistant.components.mqtt: debug
    
# Includes
sensor: !include sensors.yaml
switch: !include switches.yaml
camera: !include cameras.yaml
group: !include groups.yaml
script: !include scripts.yaml
automation: !include automation.yaml
light: !include lights.yaml

# Text to speech
tts:
  platform: google

# media_player:
#   - platform: kodi
#     host: 192.168.1.100
#     port: 80
#     username: kodi
#     password: kodi

notify:
  - platform: pushbullet
    api_key: !secret pushbullet_api_key

recorder:
  # Delete events and states older than 2 weeks
  purge_days: 14

input_boolean:
  kitchen_room_already_turned_on:
    name: Kitchen Room Already Turned On
    initial: off

panel_custom:
  - name: textpanel
    sidebar_title: "IR & RC sensors"
    sidebar_icon: mdi:book-open
    config:
      who: test